apiVersion: v1
kind: Secret
metadata:
  name: checklister-secret
type: Opaque
data:
  secret_key_base: JmkzWmhRN2tTZ0oyNUxMQFVFZ00kM1FzQ0w5YzdqMkFhbnA1KiZuN2UqNCY1UCp0SGZmNVdhc3dMNXQjWHZ5Qg==
  phx_host: "ZXhhbXBsZS5jb20="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checklister-configmap
data:
  database_name: checklister_prod
  database_hostname: "postgres"
  database_pool_size: "10"
  phx_host: "127.0.0.1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklister
spec:
  selector:
    matchLabels:
      app: checklister
  template:
    metadata:
      labels:
        app: checklister
    spec:
      containers:
      - name: checklister
        image: maximkuzmin/checklister:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: checklister-configmap
                key: database_name

          - name: DATABASE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: checklister-configmap
                key: database_hostname

          - name: DATABASE_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                name: checklister-configmap
                key: database_pool_size

          - name: PHX_HOST
            valueFrom:
              configMapKeyRef:
                name: checklister-configmap
                key: phx_host

          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: checklister-secret
                key: secret_key_base

          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 4000
