apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checklister-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checklister
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checklister-ingress
  labels:
    name: checklister-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: checklister.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: checklister
            port:
              number: 4000


---
apiVersion: v1
kind: Service
metadata:
  name: checklister-service
spec:
  type: NodePort
  selector:
    app: checklister
  ports:
  - port: 4000
    targetPort: 4000

---
apiVersion: v1
kind: Secret
metadata:
  name: checklister-secret
type: Opaque
data:
  SECRET_KEY_BASE: JmkzWmhRN2tTZ0oyNUxMQFVFZ00kM1FzQ0w5YzdqMkFhbnA1KiZuN2UqNCY1UCp0SGZmNVdhc3dMNXQjWHZ5Qg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checklister-configmap
data:
  DATABASE_NAME: checklister_prod
  DATABASE_HOSTNAME: "postgres"
  DATABASE_POOL_SIZE: "10"
  PHX_HOST: "checklister.info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklister
spec:
  selector:
    matchLabels:
      app: checklister
  template:
    metadata:
      labels:
        app: checklister
    spec:
      initContainers:
        - name: checklister-init-migrate
          image: maximkuzmin/checklister:latest
          imagePullPolicy: "Always"
          command: ["/app/bin/migrate"]
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: checklister-configmap
            - secretRef:
                name: checklister-secret
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

      containers:
      - name: checklister
        image: maximkuzmin/checklister:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: checklister-configmap
          - secretRef:
              name: checklister-secret
        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: "/liveness"
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/readiness"
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 3

